import { InvokeModelCommand } from "@aws-sdk/client-bedrock-runtime";
import { bedrockClient } from "../config/bedrock.js";
import { MENTOR_SYSTEM_PROMPT } from "../utils/bedrockPrompts.js";

interface AnalysisResult {
  issueSummary: string;
  rootCauseConcept: string;
  learningHint: string;
  suggestedAction: string;
}

export const analyzeLogWithBedrock = async (logContent: string): Promise<AnalysisResult> => {
  try {
    // Model ID for Claude 3 Haiku on AWS Bedrock
    const modelId = "anthropic.claude-3-haiku-20240307-v1:0";

    const payload = {
      anthropic_version: "bedrock-2023-05-31",
      max_tokens: 1000,
      system: MENTOR_SYSTEM_PROMPT,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: `Here is the student's terminal error log / query context:\n\n${logContent}`,
            },
          ],
        },
      ],
    };

    const command = new InvokeModelCommand({
      modelId,
      contentType: "application/json",
      accept: "application/json",
      body: JSON.stringify(payload),
    });

    const response = await bedrockClient.send(command);

    // Decode binary response payload
    const responseBody = new TextDecoder().decode(response.body);
    const parsedResponse = JSON.parse(responseBody);

    // Extract text from Anthropic response payload
    const rawContent = parsedResponse.content?.[0]?.text || "{}";

    // Parse internal JSON response generated by AI mentor
    const result: AnalysisResult = JSON.parse(rawContent);
    return result;
  } catch (error) {
    console.error("Bedrock AI Service Error:", error);

    // Fallback response if AWS Bedrock fails or keys are temporary/mock
    return {
      issueSummary: "Failed to fetch response from AWS Bedrock AI.",
      rootCauseConcept: "Service connection issue or invalid credentials.",
      learningHint: "Check if AWS credentials in .env are active and correct.",
      suggestedAction: "Verify AWS account status and Bedrock model access.",
    };
  }
};